### ISSUE TITLE
SPRINT 1

### ISSUE THREAD

**Issue by alinevenceslau** [filipeandrev/Final_pp2#20]
- [x] Cadastro de aluno.
- [x] Cadastro de funcionário.
- [ ] Cadastro de veículo ( Vai ter que listar meus veículos também).
- [x] Módulo de autenticação ( login).
- [ ] Vínculo de aluno ou funcionário com o (s) veículo(s).
- [ ] Cadastro do estacionamento com o quantitativo de vagas por tipo de veículos (
admin do sistema).
- [ ] Realizar check-in na entrada do veículo ( caso haja vagas).
- [ ] Realizar check-out na saída do veículo ( liberando uma vaga).
